// manage student
export const SAVE_SET_LIST_STUDENT = "SAVE_SET_LIST_STUDENT";
export const SAVE_SET_SELECTED_STUDENT = "SAVE_SET_SELECTED_STUDENT";
export const SAVE_CREATE_STUDENT = "SAVE_CREATE_STUDENT";
export const SAVE_UPDATE_STUDENT = "SAVE_UPDATE_STUDENT";
export const SAVE_DELETE_STUDENT = "SAVE_DELETE_STUDENT";
export const SET_MODAL_STUDENT_VISIBLE = "SET_MODAL_STUDENT_VISIBLE";

// manage teacher
export const SAVE_SET_LIST_TEACHER = "SAVE_SET_LIST_TEACHER";
export const SAVE_SET_SELECTED_TEACHER = "SAVE_SET_SELECTED_TEACHER";
export const SAVE_CREATE_TEACHER = "SAVE_CREATE_TEACHER";
export const SAVE_UPDATE_TEACHER = "SAVE_UPDATE_TEACHER";
export const SAVE_DELETE_TEACHER = "SAVE_DELETE_TEACHER";
export const SET_MODAL_TEACHER_VISIBLE = "SET_MODAL_TEACHER_VISIBLE";
